<?php
$config = array('clientes' => array(
                                array(
                                    'field'=>'vw_cliente_tipo',
                                    'label'=>'Tipo de Cliente',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_nome_razao',
                                    'label'=>'nomeCliente',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_apelido_fantasia',
                                    'label'=>'Apelido / Nome Fantasia',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_cpf_cnpj',
                                    'label'=>'CPF/CNPJ',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_rg_inscricao',
                                    'label'=>'RG / Inscrição Estadual',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_genero',
                                    'label'=>'Genero',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_tel01',
                                    'label'=>'Telefone 01',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_tel02',
                                    'label'=>'Telefone 02',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_email',
                                    'label'=>'Email',
                                    'rules'=>'required|trim|valid_email'
                                ),
                                array(
                                    'field'=>'vw_cliente_cep',
                                    'label'=>'CEP',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_logradouro',
                                    'label'=>'Logradouro',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_numero',
                                    'label'=>'Numero',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_bairro',
                                    'label'=>'Bairro',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_cidade',
                                    'label'=>'Cidade',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_cliente_estado',
                                    'label'=>'Estado',
                                    'rules'=>'required|trim'
                                ))
                ,
                'servicos' => array(array(
                                    'field'=>'nome',
                                    'label'=>'Nome',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'descricao',
                                    'label'=>'',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'preco',
                                    'label'=>'',
                                    'rules'=>'required|trim'
                                ))
                ,
                'produtos' => array(
                                array(
                                    'field'=>'vw_produto_marca',
                                    'label'=>'',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'vw_produto_descricao',
                                    'label'=>'',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_produto_partnumber',
                                    'label'=>'',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'vw_produto_unid_medida',
                                    'label'=>'Unidade',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_produto_preco_compra',
                                    'label'=>'Preo de Compra',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_produto_preco_venda',
                                    'label'=>'Preo de Venda',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_produto_estoque_atual',
                                    'label'=>'Estoque',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vw_produto_estoque_minimo',
                                    'label'=>'Estoque Mnimo',
                                    'rules'=>'trim'
                                ))
                ,
                 'equipamentos' => array(array(
                                    'field'=>'vw_equipamento_nome',
                                    'label'=>'',
                                    'rules'=>'required|trim'
                                ))
                ,

                'marcas' => array(array(
                                    'field'=>'vw_marca_nome',
                                    'label'=>'',
                                    'rules'=>'required|trim'
                                ),                                
                                array(
                                    'field'=>'vw_marca_website',
                                    'label'=>'',
                                    'rules'=>'trim'
                                ))
                ,
                'enviarwhatsapp' => array(array(
                                    'field'=>'vw_marca_nome',
                                    'label'=>'',
                                    'rules'=>'required|trim'
                                ),                                
                                array(
                                    'field'=>'vw_marca_website',
                                    'label'=>'',
                                    'rules'=>'trim'
                                ))
                ,
                'usuarios' => array(array(
                                    'field'=>'nome',
                                    'label'=>'Nome',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'rg',
                                    'label'=>'RG',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'cpf',
                                    'label'=>'CPF',
                                    'rules'=>'required|trim|is_unique[tb_usuario.usuario_cpf]'
                                ),
                                array(
                                    'field'=>'rua',
                                    'label'=>'Rua',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'numero',
                                    'label'=>'Numero',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'bairro',
                                    'label'=>'Bairro',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'cidade',
                                    'label'=>'Cidade',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'estado',
                                    'label'=>'Estado',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'email',
                                    'label'=>'Email',
                                    'rules'=>'required|trim|valid_email|is_unique[tb_usuario.usuario_email]'
                                ),
                                array(
                                    'field'=>'senha',
                                    'label'=>'Senha',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'telefone',
                                    'label'=>'Telefone',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'situacao',
                                    'label'=>'Situacao',
                                    'rules'=>'required|trim'
                                ))
                ,
                'os' => array(array(
                                    'field'=>'dataInicial',
                                    'label'=>'DataInicial',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'dataFinal',
                                    'label'=>'DataFinal',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'garantia',
                                    'label'=>'Garantia',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'descricaoProduto',
                                    'label'=>'DescricaoProduto',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'defeito',
                                    'label'=>'Defeito',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'status',
                                    'label'=>'Status',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'observacoes',
                                    'label'=>'Observacoes',
                                    'rules'=>'trim'
                                ),
                                array(
                                    'field'=>'clientes_id',
                                    'label'=>'clientes',
                                    'rules'=>'trim|required'
                                ),
                                array(
                                    'field'=>'usuarios_id',
                                    'label'=>'usuarios_id',
                                    'rules'=>'trim|required'
                                ),
                                array(
                                    'field'=>'laudoTecnico',
                                    'label'=>'Laudo Tecnico',
                                    'rules'=>'trim'
                                ))

                  ,
                'tiposUsuario' => array(array(
                                    'field'=>'nomeTipo',
                                    'label'=>'NomeTipo',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'situacao',
                                    'label'=>'Situacao',
                                    'rules'=>'required|trim'
                                ))

                ,
                'receita' => array(array(
                                    'field'=>'descricao',
                                    'label'=>'Descrição',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'valor',
                                    'label'=>'Valor',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vencimento',
                                    'label'=>'Data Vencimento',
                                    'rules'=>'required|trim'
                                ),
                        
                                array(
                                    'field'=>'cliente',
                                    'label'=>'Cliente',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'Tipo',
                                    'rules'=>'required|trim'
                                ))
                ,
                'despesa' => array(array(
                                    'field'=>'descricao',
                                    'label'=>'Descrição',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'valor',
                                    'label'=>'Valor',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'vencimento',
                                    'label'=>'Data Vencimento',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'fornecedor',
                                    'label'=>'Fornecedor',
                                    'rules'=>'required|trim'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'Tipo',
                                    'rules'=>'required|trim'
                                ))
                ,
                'vendas' => array(array(

                                    'field' => 'dataVenda',
                                    'label' => 'Data da Venda',
                                    'rules' => 'required|trim'
                                ),
                                array(
                                    'field'=>'clientes_id',
                                    'label'=>'clientes',
                                    'rules'=>'trim|required'
                                ),
                                array(
                                    'field'=>'usuarios_id',
                                    'label'=>'usuarios_id',
                                    'rules'=>'trim|required'
                                ))
        );
